### ISSUE TITLE
Negative luminosity/energies leads to errors in Detector.detector_hits

### ISSUE THREAD

**Issue by sgriswol** [IceCubeOpenSource/ASTERIA#17]
Errors arise due to negative mean neutrino energies and luminosity near the bounce time. This is a result of the interpolation in the source module.

**Comment by sybenzvi** [comment]
I noticed this seems to be caused by the use of the `InterpolatedUnivariateSpline` class from scipy. We should probably switch to `interp1d` in `source.py`.

**Comment by sgriswol** [comment]
Fixed by commit `ca124ae` to master
