### ISSUE TITLE
No standard progenitor distance for files saved by IO module

### ISSUE THREAD

**Issue by rcross2** [IceCubeOpenSource/ASTERIA#45]
Current operations to save a processed simulation is:

```
E_per_V_1kpc =  E_per_V * ccsn.progenitor_distance.to(u.kpc).value**2
io.save(conf, Interactions, Hierarchy, Flavor, Enu.value, time.value, \
                                    E_per_V_1kpc, force=True)
```

IO module should do the conversion to 1kpc so that data files are at a standard distance.

**Comment by sgriswol** [comment]
As of #52 this can now be handled by the `SimulationHandler` class.
Example:
```from asteria import config
from asteria.handler import SimulationHandler

conf = config.load_config('path-to-asteria/data/config/default.yaml')
sim = SimulationHandler(conf)
sim.load()
sim.E_per_V 
```
This assumes a simulation has already been saved. 
`sim.save()` will scale the energy deposition per volume to a progenitor at 1kpc, and then save the result to file.
`sim.load()` will load the scaled energy deposition per volume and re-scale it to the distance specified by the `source.progenitor.distance.distance` node of the `conf` object.
