### ISSUE TITLE
ASTERIA is Missing Command-line functionality of USSR

### ISSUE THREAD

**Issue by sgriswol** [IceCubeOpenSource/ASTERIA#9]
(Request from Lutz) In USSR, it was possible to easily iterate through a wide variety of simulation configurations and to take commands from terminal. ASTERIA lacks this functionality
- Implement command line functionality for ASTERIA
Potential new Features:
1) New fields in configuration YAML (OR new top-level config simulation YAML) which describes ALL options of simulation.. 
2) New methods (in IO.py) to parse command-line options 
3) New Methods (in IO.py) to parse an iterable of options within yaml file or at command line
4) New Methods/objects to run the full simulation (Potentially set up methods to individually handle steps outlined in detector_response.ipynb)

**Comment by sybenzvi** [comment]
This has been implemented in the `scripts` branch and merged with `master`.
